# Use root/example as user/password credentials
version: '3.1'

services:
  node:
    user: "${UID}:${GID}"
    image: node
    volumes:
      - ./home:/usr/src/app
    ports:
      - 52273:3000
    stdin_open: true
    tty: true
    working_dir: /usr/src/app

  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MARIADB_USER: "${MARIADB_USER}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
