# Use root/example as user/password credentials
version: '3.1'

services:
  node:
    user: "${UID}:${GID}"
    image: node
    volumes:
      - ./home:/usr/src/app
    ports:
      - 52273:3000
    stdin_open: true
    tty: true

  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
